---
# seed: 1

node_count: 100
simulation_time_in_seconds: 31622400

chain_reorganization_threshold: 2
average_network_latency_in_seconds: 6
average_transactions_per_second: 4
maximum_transaction_per_block: 3000

proof_of_work:
  enabled: true
  epoch_length: 2016
  average_block_frequency_in_seconds: 600
