---
node_count: 4
simulation_time_in_seconds: 100000000

average_network_latency_in_seconds: 6
average_block_frequency_in_seconds: 600
chain_reorganization_threshold: 0

proof_of_burn_every_nth_block: 2
