---
node_count: 1000
simulation_time_in_seconds: 1000000

average_network_latency_in_seconds: 6
average_block_frequency_in_seconds: 600
chain_reorganization_threshold: 1

proof_of_burn_every_nth_block: 2
